### ISSUE TITLE
Segementation fault while running eqtlbma_bf

### ISSUE THREAD

**Issue by kauralasoo** [timflutre/eqtlbma#15]
Hi,

I have a dataset of gene expression from 31 individuals measured in 4 conditions (A,B,C,D). I've installed the latest version of eqtlbma from the master branch and I've verified that /tests/test_basic.bash complete without errors. I've also beeb able to successfully complete the tutorial on simulated data without any problems.

However, when I'm trying to run it on my own data it works well for some genes, but for others I get segmentation faults that sometimes randomly disappear. For example the following command produces segmation fault > 90% of the time:

eqtlbma_bf --geno eqtlbma/list_genotypes.txt \
 --scoord eqtlbma/snp_coords.bed.gz \
 --exp eqtlbma/list_explevels_HLA.txt \
 --gcoord eqtlbma/HLA_coord.txt \
 --anchor TSS \
 --cis 500000 \
 --out eqtlbma/output/subset_test \
 --analys join --gridL eqtlbma/grid_phi2_oma2_general.txt \
 --gridS eqtlbma/grid_phi2_oma2_with-configs.txt \
 --bfs all \
 --error mvlr \
 -v 3

test for association between each pair gene-SNP ...
analysis=join likelihood=normal error_model=mvlr prop_cov_errors=0.50 anchor=TSS radius=500000
gene ENSG00000196735
339 cis SNP(s)
ENSG00000196735 (4 subgroups) versus exm-rs3830076 (4 subgroups)
ENSG00000196735 (4 subgroups) versus exm534565 (4 subgroups)
ENSG00000196735 (4 subgroups) versus rs4713505;exm-rs4713505 (4 subgroups)
ENSG00000196735 (4 subgroups) versus exm-rs204999 (4 subgroups)
ENSG00000196735 (4 subgroups) versus exm-rs3130279 (4 subgroups)
ENSG00000196735 (4 subgroups) versus exm-rs4713506 (4 subgroups)
...
ENSG00000196735 (4 subgroups) versus exm-rs2395110 (4 subgroups)
ENSG00000196735 (4 subgroups) versus exm-rs6936204 (4 subgroups)
ENSG00000196735 (4 subgroups) versus exm-rs3115573 (4 subgroups)
Segmentation fault

I'm happy to send you the example data for you to replicate the issue.

Best wishes,
Kaur

**Comment by timflutre** [comment]
Hi,
when you look at what is in stdout, between START..." and "test for association...", did you notice everything suspect? In terms of number of samples, etc?
Otherwise, can you send me the data?
Tim

**Comment by kauralasoo** [comment]
Hi Tim,

Sorry for not replying earlier - I was away for a couple of days. I double-checked the STDOUT and there is nothing obviously suspicious until the segmentation fault. I've sent the data to your gmail address.

Thanks for looking into this,
Kaur

**Comment by timflutre** [comment]
Hi Kaur,
I finally found some time to have a look. If I'm right, the bug occurs when discarding SNPs with missing genotypes in at least one subgroup when the genotype file is in the "custom" format ([here](https://github.com/timflutre/eqtlbma/blob/master/src/eqtlbma/quantgen/data_loader.cpp#L961)).
I will try to fix this in July. For the time being, I would advise you to remove all SNPs with missing values from the genotype file. And I hope it'll work. Again, sorry for that...

**Comment by timflutre** [comment]
Gao Wang contributed a bug fix which is now incorporated into the master branch. Can you try on your data?

**Comment by kauralasoo** [comment]
Thanks Tim and Gao,

It seems to be working now.

Kaur

**Comment by timflutre** [comment]
Great! And sorry again for the delay...
