### ISSUE TITLE
cblas_sgemm() function

### ISSUE THREAD

**Issue by mingfang618** [timflutre/eqtlbma#21]
Hello,

When I run the package it produces the error below:
"configure: error: unable to find the gslcblas library with the cblas_sgemm() function"
Is it due to the gsl not being linked?

ps:the sever has the gsl installed.
Thanks!
Ming

**Comment by timflutre** [comment]
I think you have a version of the GSL which is too old, that is, it doesn't have the cblas_sgemm function. You hence need to upgrade the GSL to 1.15 at least.
