### ISSUE TITLE
Question about configuration number assignment

### ISSUE THREAD

**Issue by snaqvi1990** [timflutre/eqtlbma#26]
Hi, 

I am posting this question here because I am having trouble viewing/accessing the mailing list.

In the bayes factor file outputted by eqtlbma_bf (or indeed any reference to a configuration), is there a record of which subgroup each number in the various configuration strings corresponds to? I.e. if i have 4 subgroups, "Skin", "Heart", "Liver", and "Lung", a configuration of 1-3 corresponds to activity in which two tissues? looking at a few examples, it doesn't seem to be based on the order in which subgroup files are listed in --exp or --inss, but maybe I'm missing something obvious.

Thanks,
Sahin

**Comment by timflutre** [comment]
Hello,
This information is indicated on stdout as long as verbose > 0.

**Comment by snaqvi1990** [comment]
Got it, thanks. I had one additional question: I have run eqtlbma_bf with --sin, and after running eqtlbma_hm and eqtlbma_avg_bfs I can get the BFs/posteriors for each of the singleton configurations just fine. However, with --sin eqtlbma_bf also computes BFs for 3 types of "general" configurations (the general, fixed-effect, and maximum heterogeneity models). How would I get the averaged BFs/posteriors for each of those 3 general configurations? eqtlbma_hm seems to crash if I specify --dim 15 (i.e. 12 singletons plus the 3 general configurations), so maybe I'm missing something...

**Comment by timflutre** [comment]
There is no notion of configuration for the 3 "general" Bayes factors. So you can't average them over configurations. But you can average them over grid values, using `eqtlbma_avg_bfs`.

(Sorry for my late answer, I was away for two weeks.)

**Comment by timflutre** [comment]
Is this issue solved for you?

**Comment by snaqvi1990** [comment]
Yes I've figured it out. Thanks
