### ISSUE TITLE
Prepare a new release?

### ISSUE THREAD

**Issue by molpopgen** [timflutre/eqtlbma#27]
Following up on my comments in #22, the release 1.3.2 also fails to compile under GSL 2.1 (the API change referred to in #22 changed in 2.0 (see [here](http://git.savannah.gnu.org/cgit/gsl.git/tree/NEWS)).  A new release would help us update the bioconda package ASAP.

**Comment by timflutre** [comment]
See my [comment](https://github.com/timflutre/eqtlbma/issues/22#issuecomment-381624413) closing issue #22.
